// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Domain.Models;

public partial class Products_Above_Average_Price
{
    public string ProductName { get; set; }

    public decimal? UnitPrice { get; set; }
}