using System.Web;

namespace PartTwo.Workflow.Infrastructure
{
    public class InfoHandler : IHttpHandler
    {
        public void ProcessRequest(HttpContext context)
        {
            if (context.Request.RawUrl == "/Test/Index")
            {
                context.Server.TransferRequest("/Home/Index");
            }
            else
            {
                context.Response.Write("Content generated by InfoHandler");
            }
        }
        public bool IsReusable
        {
            get { return false; }
        }
    }
}