// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.DomainModel.Models;

public partial class Category_Sales_for_1997
{
    public string CategoryName { get; set; }

    public decimal? CategorySales { get; set; }
}