// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.DomainModel.Models;

public partial class Current_Product_List
{
    public int ProductID { get; set; }

    public string ProductName { get; set; }
}