// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.DomainModel.Models
{
    public partial class GetNorthwindEmployeesResult
    {
        public int EmployeeID { get; set; }
        [StringLength(30)]
        public string Title { get; set; }
        [StringLength(31)]
        public string FullName { get; set; }
        [StringLength(30)]
        public string HireDate { get; set; }
        [StringLength(43)]
        public string Location { get; set; }
        [StringLength(24)]
        public string PhoneNumber { get; set; }
    }
}
