@AdventureWorks.ServiceAPI_HostAddress = https://localhost:7061
@id=16


GET {{AdventureWorks.ServiceAPI_HostAddress}}/api/department

###

GET {{AdventureWorks.ServiceAPI_HostAddress}}/api/department/{{id}}

###