name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Debug — list repository root and Portfolio
        run: |
          echo "Repository root:"
          ls -la
          echo "--- Portfolio contents ---"
          ls -la Portfolio || true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          # Adjust SDK version if you need a different one (e.g. 7.0.x)
          dotnet-version: '8.0.x'

      - name: Prepare and build Blazor app (dotnet publish)
        id: prepare
        run: |
          # default app_location (change if your app is not in Portfolio)
          echo "app_location=Portfolio" >> $GITHUB_OUTPUT

          # find a project file inside Portfolio
          proj=$(ls Portfolio/*.csproj 2>/dev/null | head -n1 || true)
          if [ -n "$proj" ]; then
            echo "Found project: $proj"
            # Restore and publish into Portfolio/publish
            dotnet restore "$proj"
            dotnet publish "$proj" -c Release -o Portfolio/publish

            # Detect where index.html landed
            deploy_output=""
            if [ -f "Portfolio/publish/index.html" ]; then
              deploy_output="publish"
            elif [ -f "Portfolio/publish/wwwroot/index.html" ]; then
              deploy_output="publish/wwwroot"
            else
              # attempt to find any index.html under publish and use its parent folder
              found=$(find Portfolio/publish -type f -name "index.html" -print -quit || true)
              if [ -n "$found" ]; then
                # derive relative folder from Portfolio/
                parent_dir=$(dirname "$found")
                # make it relative to Portfolio
                rel=${parent_dir#Portfolio/}
                # if parent_dir == Portfolio then rel becomes parent_dir; handle that
                if [ "$rel" = "$parent_dir" ]; then
                  rel=""
                fi
                deploy_output="$rel"
              fi
            fi

            if [ -n "$deploy_output" ]; then
              echo "Detected artifact folder relative to app_location: '${deploy_output}'"
              echo "deploy_output=${deploy_output}" >> $GITHUB_OUTPUT
            else
              echo "::warning::No index.html detected in Portfolio/publish. If this is a Blazor Server app, Azure Static Web Apps is not a supported host; consider an Azure Web App instead."
              # leave empty so user can set output_location explicitly
              echo "deploy_output=" >> $GITHUB_OUTPUT
            fi
          else
            echo "::warning::No .csproj found in Portfolio. Checking for static index.html..."
            if [ -f "Portfolio/index.html" ]; then
              echo "Found Portfolio/index.html — will deploy Portfolio root"
              echo "deploy_output=" >> $GITHUB_OUTPUT
            else
              echo "::warning::No .csproj and no Portfolio/index.html found. Check app_location or add build steps."
              echo "deploy_output=" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Fallback: try specific token then generic token
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_GRASS_0502E270F || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations - update these to match your project ######
          # app_location is the folder containing your source (relative to repo root)
          app_location: "Portfolio"
          # output_location is relative to app_location; empty string deploys app_location root.
          output_location: ${{ steps.prepare.outputs.deploy_output }}
          # We built the app ourselves (dotnet publish), so skip the Oryx app build step
          skip_app_build: true
          # If you have an API folder (Azure Functions), set it here. Otherwise set to "".
          api_location: "Api"
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_GRASS_0502E270F || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
