name: Build and deploy .NET Core application to Web App personal-portfolio
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]
  push:
    branches: [main]
env:
  AZURE_STATIC_WEBAPP_NAME: personal-portfolio
  APP_DIRECTORY: Portfolio/portfolio.main
  API_DIRECTORY: ''
  OUTPUT: wwwroot
  # For pushes to main, prefer production (or remove this line entirely)
  DEPLOYMENT_ENVIRONMENT: production
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Show repo layout (helps diagnose path issues if it fails again)
      run: |
        pwd
        ls -la
        ls -la Portfolio/portfolio.main || true
    - id: builddeploy
      name: Build And Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.personal_portfolio_SPN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: upload
        deployment_environment: ${{ env.DEPLOYMENT_ENVIRONMENT }}
        app_location: ${{ env.APP_DIRECTORY }}
        api_location: ${{ env.API_DIRECTORY }}
        output_location: ${{ env.OUTPUT }}
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Close Pull Request Job
    runs-on: ubuntu-latest
    steps:
    - id: closepullrequest
      name: Close Pull Request
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.personal_portfolio_SPN }}
        action: close
        repo_token: ${{ secrets.GITHUB_TOKEN }}
