name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Blazor WASM
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WASM
        run: dotnet publish Portfolio/portfolio.main/portfolio.main.csproj -c Release -o publish

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Portfolio/portfolio.main"
          output_location: "publish/wwwroot"